environments:
  default:
    secrets:
      - ../secrets/config/dex.yaml
repositories:
  - name: stable
    url: https://charts.helm.sh/stable
releases:
  - name: dex
    chart: stable/dex
    namespace: dex
    createNamespace: true
    wait: true
    version: 2.15.2
    values:
      - ../config/dex.yaml.gotmpl
