repositories:
  - name: loki
    url: https://grafana.github.io/loki/charts
releases:
  - name: loki
    chart: loki/loki
    namespace: loki
    createNamespace: true
    version: 2.1.1
    wait: true
    timeout: 300
    atomic: true
    values:
      - ../config/loki.yaml
  - name: promtail
    chart: loki/promtail
    namespace: loki
    version: 2.0.2
    wait: true
    timeout: 300
    atomic: true
    values:
      - ../config/promtail.yaml
